// ─── LiveKit Access Token (via secure backend) ─────────────────────────────
//
// Tokens are generated by the `generateLiveKitToken` Firebase Function so the
// LiveKit API secret never ships in the client bundle.
//
// On native we use @react-native-firebase/functions + the native ID token. On
// web we fall back to the Firebase JS SDK callable. We use require() inside a
// Platform check (not dynamic import) to avoid Metro async-chunk issues and to
// keep native-only modules out of the web bundle.
// ─────────────────────────────────────────────────────────────────────────────

import { Platform } from 'react-native';

export interface TokenOptions {
  /** Room name to join */
  roomName: string;
  /** Display name shown to other participants */
  displayName: string;
}

/**
 * Request a LiveKit access token from the backend for the authenticated user.
 * Returns the JWT string to pass to <LiveKitRoom token={...} />.
 */
export async function generateLiveKitToken(opts: TokenOptions): Promise<string> {
  const { roomName, displayName } = opts;

  if (Platform.OS === 'web') {
    // Web: Firebase JS SDK callable (auth context attached automatically)
    const { getApp } = require('firebase/app');
    const { getFunctions, httpsCallable } = require('firebase/functions');
    const functions = getFunctions(getApp());
    const callable = httpsCallable(functions, 'generateLiveKitToken');
    const result: any = await callable({ roomName, displayName });
    return result.data.token as string;
  }

  // Native: pass the native Firebase ID token explicitly so the backend can
  // resolve the caller even if the callable auth context isn't attached.
  const { getAuth } = require('@react-native-firebase/auth');
  const currentUser = getAuth().currentUser;
  if (!currentUser) {
    throw new Error('You must be signed in to start a call.');
  }
  const idToken = await currentUser.getIdToken();

  const { getFunctions, httpsCallable } = require('@react-native-firebase/functions');
  const callable = httpsCallable(getFunctions(), 'generateLiveKitToken');
  const result: any = await callable({ roomName, displayName, idToken });
  return result.data.token as string;
}
